### ISSUE TITLE
genus level average bar plot 

### ISSUE THREAD

**Issue by khemlalnirmalkar** [sbslee/dokdo#14]
Hi @sbslee ,
Thanks for your codes, much easier to make bar plots,
Please can you also suggest, how to make an average of all samples from each group and make a bar plot at the genus level from qzv file?
Thanks

**Comment by sbslee** [comment]
Thanks for the idea, I will work on this.

**Comment by khemlalnirmalkar** [comment]
Yes, please that will be great.  Thanks

**Comment by sbslee** [comment]
@khemlalnirmalkar,

As you can see below, I added the `group` option to the `taxa_abundance_bar_plot` method, which will create a bar for each group instead of each sample. This is implemented in dokdo-1.9.0. Please install Dokdo again in order to use this feature. If you have any questions regarding the update, please let me know. I also updated Dokdo API to reflect this change.

![taxa_abundance_bar_plot-11](https://user-images.githubusercontent.com/21111749/120991330-7a072600-c7bc-11eb-8efb-74dd4993149b.png)

```
dokdo.taxa_abundance_bar_plot(qzv_file,
                              level=6,
                              count=8,
                              group='body-site',
                              figsize=(10, 7),
                              legend_short=True,
                              artist_kwargs=dict(show_legend=True))
plt.tight_layout()
```

**Comment by khemlalnirmalkar** [comment]
Thank you so much, for the quick action,
I could replicate the plot.

**Comment by sbslee** [comment]
@khemlalnirmalkar,

First off, you can easily change the font size of group labels right now:

```
qzv_file = '/Users/sbslee/Desktop/dokdo/data/moving-pictures-tutorial/taxa-bar-plots.qzv'
dokdo.taxa_abundance_bar_plot(qzv_file,
                              level=6,
                              count=8,
                              group='body-site',
                              figsize=(10, 7),
                              legend_short=True,
                              artist_kwargs=dict(show_legend=True, xticklabels_fontsize=20))
plt.tight_layout()
```

![example1](https://user-images.githubusercontent.com/21111749/121005273-9f9b2c00-c7ca-11eb-825e-7dfcd31d771a.png)

For more details, please see the [Title, Axis, Legend, Font Size section](https://dokdo.readthedocs.io/en/latest/dokdo_api.html#title-axis-legend-font-size) in Dokdo API.

As for the order of group names, I agree it'd be nice to be able to manually provide an order (or subset the groups). That's why I created a development branch `1.10.0-dev` which implements the `group_order` option to the `taxa_abundance_bar_plot` method:

```
qzv_file = '/Users/sbslee/Desktop/dokdo/data/moving-pictures-tutorial/taxa-bar-plots.qzv'
dokdo.taxa_abundance_bar_plot(qzv_file,
                              level=6,
                              count=8,
                              group='body-site',
                              group_order=['right palm', 'left palm', 'gut'],
                              figsize=(10, 7),
                              legend_short=True,
                              artist_kwargs=dict(show_legend=True, xticklabels_fontsize=20))
plt.tight_layout()
```

![example2](https://user-images.githubusercontent.com/21111749/121005445-cbb6ad00-c7ca-11eb-9884-c34265c81630.png)

In order to use this new feature, you have to install the development version of Dokdo:

```
$ git clone https://github.com/sbslee/dokdo
$ cd dokdo
$ git checkout 1.10.0-dev
$ pip uninstall dokdo
$ pip install .
```

Let me know if you have any further questions/requests.

**Comment by khemlalnirmalkar** [comment]
awesome, thank you so much!! i will use development version.
